# Generated by Django 5.1.7 on 2025-03-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dividimos_app', '0003_usuario_pais_alter_usuario_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='aporte',
            name='precio_mercaderia',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
