# Generated by Django 5.1.7 on 2025-04-10 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dividimos_app', '0005_alter_usuario_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aporte',
            name='dinero',
        ),
        migrations.RemoveField(
            model_name='aporte',
            name='evento',
        ),
        migrations.RemoveField(
            model_name='aporte',
            name='mercaderia',
        ),
        migrations.RemoveField(
            model_name='aporte',
            name='precio_mercaderia',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='creador',
        ),
        migrations.RemoveField(
            model_name='invitado',
            name='telefono',
        ),
        migrations.AddField(
            model_name='aporte',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='aporte',
            name='tipo',
            field=models.CharField(choices=[('dinero', 'Dinero'), ('mercancia', 'Mercancía')], default='dinero', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aporte',
            name='valor_estimado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='lugar',
            field=models.CharField(default='Ingresa una ubicación', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invitado',
            name='agasajado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invitado',
            name='apellido',
            field=models.CharField(default='Apellido', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invitado',
            name='celular',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invitado',
            name='usuario_asociado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evento',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='invitado',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_recaudado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_gastos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('aportes_individuales', models.JSONField(default=dict)),
                ('division_gastos', models.JSONField(default=dict)),
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado', to='dividimos_app.evento')),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
